apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-demo
  namespace: rca-demo
spec:
  replicas: 1
  selector: {matchLabels: {app: oom-demo}}
  template:
    metadata: {labels: {app: oom-demo}}
    spec:
      containers:
      - name: worker
        image: busybox:1.36
        command: ["sh","-c"]
        args: ["dd if=/dev/zero of=/dev/shm/blob bs=1M count=256; sleep 3600"]
        resources:
          requests: {memory: 16Mi}
          limits: {memory: 32Mi}
